Remove metallb from test environment (#167)
With https://github.com/datastax/pulsar-helm-chart/pull/162 merged, we no longer need the Metal LB solution.

Note that the current helm chart CI is failing because the download is unavailable:


>Setup metallb in k8s
error: unable to read URL "https://raw.githubusercontent.com/metallb/metallb/master/manifests/namespace.yaml", server reported 404 Not Found, status code=404